# Generated by Django 4.2 on 2023-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='description',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.TextField(default='unknown', verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
    ]
