# Generated by Django 4.2.4 on 2023-11-02 15:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Play",
            fields=[
                ("play_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateTimeField(default=datetime.datetime(2020, 9, 1, 16, 0)),
                ),
                ("sessions_number", models.PositiveIntegerField(default=1)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "verbose_name": "Постановка",
                "verbose_name_plural": "Постановки",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "need_pass",
                    models.BooleanField(default=False, verbose_name="Нужен пропуск"),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Отчество"
                    ),
                ),
                ("vk_link", models.URLField(verbose_name="Ссылка на ВК")),
                (
                    "preferable_mates",
                    models.TextField(verbose_name="Предпочтения по сессии"),
                ),
                (
                    "preferable_role",
                    models.TextField(verbose_name="Предпочтения по роли"),
                ),
                (
                    "first_game",
                    models.BooleanField(verbose_name="Это твоя первая игра?"),
                ),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plays.play"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
