# Generated by Django 4.2.4 on 2023-09-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_game_image"),
        ("plays", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="games.game"
            ),
        ),
    ]
