# Generated by Django 4.2.4 on 2023-09-20 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_game_image"),
        ("plays", "0002_alter_play_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("surname", models.CharField(max_length=50, verbose_name="Фамилия")),
                ("need_pass", models.BooleanField()),
                (
                    "patronymic",
                    models.CharField(max_length=50, verbose_name="Отчество"),
                ),
                ("vk_link", models.URLField(unique=True, verbose_name="Ссылка на ВК")),
                (
                    "preferable_mates",
                    models.TextField(verbose_name="Предпочтения по сессии"),
                ),
                (
                    "preferable_role",
                    models.TextField(verbose_name="Предпочтения по роли"),
                ),
                ("first_game", models.BooleanField()),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="games.game"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
