# Generated by Django 4.2.4 on 2023-09-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plays", "0004_alter_record_first_game_alter_record_need_pass_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="vk_link",
            field=models.URLField(verbose_name="Ссылка на ВК"),
        ),
    ]
