# Generated by Django 4.2.4 on 2023-10-24 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plays", "0005_alter_record_vk_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="play",
            name="year",
        ),
        migrations.AddField(
            model_name="play",
            name="time",
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
