# Generated by Django 4.2.4 on 2023-10-24 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plays", "0006_remove_play_year_play_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="day",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="play",
            name="month",
            field=models.PositiveIntegerField(default=9),
        ),
        migrations.AddField(
            model_name="play",
            name="year",
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name="play",
            name="time",
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
