# Generated by Django 4.2.4 on 2023-09-06 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_games_image_alter_games_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Games",
        ),
    ]
